curl -v -H "Content-Type: application/json" -H "Accept: application/json" --data '{"first": [1,2,3,4], "second": [3,4]}' "http://localhost:8080/api/setintersection/complex"

curl -v "http://localhost:8080/api/setintersection/simple?firstCollection=1&firstCollection=2&secondCollection=3&secondCollection=4"
curl -v "http://localhost:8080/api/setintersection/simple?firstCollection=1,2,3,4&secondCollection=3,4"
